### ISSUE TITLE
[FEAT] 채팅 관련 유닛 테스트 코드 작성 및 통합 테스트

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#10]
## 🖥️ Descriptions
 - 채팅 관련 유닛 테스트 코드를 작성하고, 백엔드와의 통합 테스트를 거치며 생기는 요청들을 처리한다.

## ✅ Todo
- [x] Chat 관련 안드로이드 테스트 코드 작성
- [x] Chatroom 관련 안드로이드 테스트 코드 작성
- [x] 백엔드와의 API 통합 테스트
