### ISSUE TITLE
[FEAT] 회원가입, 로그인, 로그아웃 UI 개발

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#2]
## 🖥️ Descriptions
 - 프론트엔드의 회원가입, 로그인, 로그아웃 UI 개발
 - 백과의 통신으로 인증 시스템 구현 

## ✅ Todo
- [x] 회원가입 UI 제작
- [x] 로그인 UI 제작
- [x] jwt 통신 시스템 구현
- [x] sharedpreference로 자동 로그인 구현

**Comment by jinjae1** [comment]
abc
