### ISSUE TITLE
[FEAT] 라이프사이클 단계별 기능 구현

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#20]
## 🖥️ Descriptions
 - 라이프사이클의 단계별 기능을 구현한다.

## ✅ Todo
- [x] 연습실 찾기 및 지도 UI 추가
- [x] 공연장 찾기 UI 추가
- [x] 공연 홍보, QR 생성 UI 추가
- [ ] 공연장, 연습실 필터링 및 검색 기능 추가
- [x] 정산하기 UI 추가
- [x] 연습실, 공연장, 정산하기 관련 service 추가
- [x] 정산하기 기능 로직 추가
- [x] 홍보하기 기능 로직 추가
