### ISSUE TITLE
[FEAT] 커뮤니티 속 공연게시판 UI 제작

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#21]
## 🖥️ Descriptions
 - 커뮤니티 속 공연게시판 UI를 제작한다.

## ✅ Todo
- [x] 공연게시판 조회 UI 추가
- [x] 공연게시판 생성 UI 추가
- [x] 공연 하나 조회 UI 추가
- [x] 공연 게시글 수정 및 삭제 UI 추가

## ☁️ ETC
 - 내용을 적어주세요
