### ISSUE TITLE
[FEAT] 채팅방에 새로운 사용자 초대

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Frontend#47]
## 🖥️ Descriptions
 - 채팅방에 새로운 멤버를 초대하는 기능
 - 개인 채팅인 경우 X
 - 단체 채팅인 경우에만, 멤버 초대 기능

## ✅ Todo
- [x] 개인채팅 vs 단체채팅 구분
- [x] 단체 채팅인 경우, 멤버 초대 기능 활성화
- [x] 멤버 초대 API 연결
- [x] 테스트

## ☁️ ETC
 -
