### ISSUE TITLE
[FEAT] 채팅 UI 및 클라이언트 제작

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#5]
## 🖥️ Descriptions
 - 채팅 관련 페이지 UI를 제작하고, 채팅 정보 수신을 위한 SSE 클라이언트를 구축한다.

## ✅ Todo
- [x] 채팅방 조회 UI 제작
- [x] 채팅방 조회 로직 구현
- [x] 개인 채팅 UI 제작
- [x] 개인 채팅 로직 구현
- [x] 멀티 채팅 UI 제작
- [x] 멀티 채팅 로직 구현
- [x] 시스템 채팅 UI 제작
- [x] 시스템 채팅 로직 구현
- [x] SSE 클라이언트 구축
- [x] #9

## ☁️ ETC
 - 채팅방 UI를 위해 viewList 사용 예정 & 채팅 말풍선 UI를 위해 나인패치 사용 예정
 - 채팅 시스템 구축을 위한 SSE 클라이언트 구현 예정
