### ISSUE TITLE
[FEAT] 라이프사이클 단체 관련 UI 및 로직 추가

### ISSUE THREAD

**Issue by soseongha** [ajou-JSL/Frontend#7]
## 🖥️ Descriptions
 - 라이프사이클 관련 기능과 UI를 추가

## ✅ Todo
- [x] 나의모음탭 단체 조회 UI 제작
- [x] 나의모음탭 단체 생성, 수정, 삭제 UI 제작
- [ ] 나의모음탭 관련 유닛 테스트 코드 추가
